# Generated by Django 3.0.8 on 2021-05-04 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedQue',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('ques_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='select_que_receiver', to=settings.AUTH_USER_MODEL)),
                ('ques_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_que_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'selected_que',
            },
        ),
        migrations.AddField(
            model_name='ansmarked',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ansmarked',
            name='markes_got',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_multiple_choice',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='selectedque',
            name='question',
            field=models.ManyToManyField(blank=True, related_name='select_set_question', to='quiz.Question'),
        ),
    ]
