# Generated by Django 3.0.8 on 2021-05-04 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210504_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ansmarked',
            old_name='markes_got',
            new_name='marks_got',
        ),
    ]
